### PR TITLE
Setup iOS PN

### LINKED ISSUE #187: Feature: Support PN on iOS devices
* [x] setup the PN on iOS
* [x] setup Firebase
* [x] code adaption

@ahoseinian the link you mentioned from Firebase, you can comment down under this issue.

### PR DESCRIPTION
**Pull request by geastwood**
* generated a key from iOS developer console
* setup certificate
* upload relevant files to firebase
* ga_pn_dev, ga_pn_prod

Closes #187

### CODE REVIEW

**Comment by ahoseinian** [comment]
@fei if you uploaded something to firebase don't we need to redownload the GoogleService-info.plist & google-service.json file again from firebase and add to project or they stay the same?

**Comment by geastwood** [comment]
Yeh. Good point, can you generate a new plist file and check it's the same? Ty

**Comment by ahoseinian** [comment]
@geastwood I checked this. there is no changes

**Comment by ahoseinian** [comment]
@geastwood pushes on IOS seems to be working on my device 🎉

**Comment by geastwood** [comment]
Awesome!

**Pull request merged**
