### PR TITLE
Issue 883 fetch council motion from litentry graph

### LINKED ISSUE #883: Fetch council motion from Litentry-graph
Upgrade council motion to graphQL APIs

### PR DESCRIPTION
**Pull request by Ekaanth**
fix #883

### CODE REVIEW

**Comment by ishrak-imam** [comment]
This branch has a lot of irrelevant changes. You need to rebase it against develop.

**Comment by silva-fj** [comment]
Is this PR ready for review? I see some incomplete changes and other things not related with Motions

**Comment by Ekaanth** [comment]
> Is this PR ready for review? I see some incomplete changes and other things not related with Motions

We need a dummy proposal that has a complex proposal to test it and, IMO we just need to test for now.

**Comment by ishrak-imam** [comment]
This [PR](https://github.com/litentry/litentry-graph/pull/133) is ready for review and once merged the work here can be continued again. It is possible to start working by spinning up a local server too.

To fetch the council motions data the following schema should be used

```
{
  substrateChainCouncilMotions {
    proposal {
      index
      meta
      method
      section
      args {
        name
        type
        value
        subCalls {
          meta
          method
          section
          args {
            name
            type
            value
          }
        }
      }
      hash
      proposer {
        ...AccountFields
      }
      beneficiary {
        ...AccountFields
      }
      payout
    }
    votes {
      threshold
      ayes {
        ...AccountFields
      }
      nays {
        ...AccountFields
      }
      end
      endTime
    }
    votingStatus {
      hasFailed
      hasPassed
      isCloseable
      isVoteable
      remainingBlocks
      remainingBlocksTime
      status
    }
  }
}
```

**Comment by Ekaanth** [comment]
> This [PR](https://github.com/litentry/litentry-graph/pull/133) is ready for review and once merged the work here can be continued again. It is possible to start working by spinning up a local server too.
> 
> To fetch the council motions data the following schema should be used
> 
> ```
> {
>   substrateChainCouncilMotions {
>     proposal {
>       index
>       meta
>       method
>       section
>       args {
>         name
>         type
>         value
>         subCalls {
>           meta
>           method
>           section
>           args {
>             name
>             type
>             value
>           }
>         }
>       }
>       hash
>       proposer {
>         ...AccountFields
>       }
>       beneficiary {
>         ...AccountFields
>       }
>       payout
>     }
>     votes {
>       threshold
>       ayes {
>         ...AccountFields
>       }
>       nays {
>         ...AccountFields
>       }
>       end
>       endTime
>     }
>     votingStatus {
>       hasFailed
>       hasPassed
>       isCloseable
>       isVoteable
>       remainingBlocks
>       remainingBlocksTime
>       status
>     }
>   }
> }
> ```

I'm working on a new PR right now.

**Comment by Ekaanth** [comment]
A new PR when the https://github.com/litentry/litentry-graph/pull/133 is merged will be submitted with the latest changes.

**Pull request closed without merging**
