### PR TITLE
Replacing bn.js with a native implementation (react-native-bignumber)

### PR DESCRIPTION
**Pull request by silva-fj**
This library replaces `bn.js` with a native implementation in c++ using JSI. 

It would be a good idea add some performance monitoring into our app to be able to measure properly this kind of improvements. I'll tackle this in a separate PR

### CODE REVIEW

**Comment by geastwood** [comment]
Should we go ahead with this?

**Review by Ekaanth — APPROVED** [review]

**Comment by Ekaanth** [comment]
> Should we go ahead with this?

Looks good to me just curious if the package is entirely ready for production.

**Comment by ishrak-imam** [comment]
> Should we go ahead with this?

I remember @franjs was willing to wait to check some metrics to see if it is really improving any performance.

After merging this https://github.com/litentry/litentry-app/pull/1092 there should be some metrics already and when this is merged we can compare. IIRC this was the reason to wait.

**Comment by silva-fj** [comment]
Yeah the plan is to compare the performance metrics to see if we get any benefit from this because it was not noticeable. I'll take a look at this soon, we can measure this locally, there is no need to wait until this is merged to see the metrics on firebase

**Comment by silva-fj** [comment]
closing in favor of https://github.com/litentry/litentry-app/pull/1133

**Pull request closed without merging**
