### PR TITLE
Support parachain token migration

### PR DESCRIPTION
**Pull request by silva-fj**
This is the initial setup to add support for token migration for our Parachains. As part of this PR we have:

- Integrated WalletConnect to interact with other wallets.
- Installed web3 to interact with the smart contracts.
- Integrated Web3 with WalletConnect (currently using a free Infura account).
- Separated for now our Main app navigation from the Parachain app navigation.
- Setup all the logic needed to migrate tokens (utils, service, etc)

I have successfully tested this setup with the hardcoded values, the transactions can be seen here:
 https://rinkeby.etherscan.io/address/0x838C543187312cc85592f43a35b03A7aCb8B273a 
(The **Approve** and **Deposit** transactions).

Note that these changes will only be available on development.

Next steps:
- Work on UI/UX to add this feature.
- Setup Infura or RPC endpoints correctly as the web3 provider.
- Add config for production (smart contract addresses, accounts, etc).
- Clean related code a little bit once we have clear the final implementation (related to https://github.com/litentry/litentry-app/issues/1015)

### CODE REVIEW

**Comment by geastwood** [comment]
Thanks for the good work, are there any difficulties pulling this off?

**Comment by silva-fj** [comment]
> Thanks for the good work, are there any difficulties pulling this off?

I don't think we will have issues. Although, I only tested it with MetaMask on Ethereum, I didn't test it for BSC.

**Comment by geastwood** [comment]
Having supported Ethereum is good enough for now.

**Review by ishrak-imam — APPROVED** [review]
Haven't tested by running the app yet. But code wise LGTM!

**Pull request merged**
