### PR TITLE
Introducing app onboarding

### LINKED ISSUE #1052: Feature: App launch onboarding
> As a new user I’d like to be guided in my first steps in the app

## **Time Frame**
Every time the user launches the app (app not in the background). In between the app loading screen and the landing on the dashboard

## **Mockup**

- ### 1st screen/card :

- ### 2nd screen/card :

- ### 3rd screen/card :

- ### 4th screen/card :

- ### 5th screen/card :

## **Image/files**
- ### 1st screen/card :
image

- ### 2nd screen/card :
image

- ### 3rd screen/card :
image

- ### 4th screen/card :
4th screen image

- ### 5th screen/card :
5th screen image

## **Copy**
- ### 1st screen/card :
**Header** : 

> Welcome !

**Body** : 

> Let me give you a quick tour and some tips to have the best start on our app

- ### 2nd screen/card : 
**Header** : 

> Pick a network

**Body** : 

> Tap on that button to switch from Polkadot to Kusama and vice-versa

- ### 3rd screen/card :
**Header** : 

> Create an account

**Body** : 

> To have full access to all the features, create or add an existing account 

- ### 4th screen/card :
**Header** : 

> Transfer fund

**Body** : 

> You can easily receive and send funds with our native wallet

- ### 5th screen/card :
**Header** : 

> Let’s go !

**Body** : 

> You can now vote, elect, make proposals, run for election ... and so much more !

### PR DESCRIPTION
**Pull request by silva-fj**
Fixes #1052 

https://user-images.githubusercontent.com/8374946/162418954-d15cf484-2a80-4c62-9dd3-d5afb851f32a.mp4

### CODE REVIEW

**Review by ishrak-imam — APPROVED** [review]
LGTM!

**Review by Ekaanth — APPROVED** [review]
Looks great 🎊

**Comment by geastwood** [comment]
* How to determine to show it, fresh install?
* Is there anywhere to manually trigger to display it again?

**Comment by silva-fj** [comment]
> * How to determine to show it, fresh install?
> * Is there anywhere to manually trigger to display it again?

Currently we will show it once (fresh install or after updating the app with this changes). If needed we can easily add something to trigger it again.

**Pull request merged**
