### PR TITLE
Fix IOS build

### PR DESCRIPTION
**Pull request by ahoseinian**
The app was not building using Xcode 12.5 because of some problems with flipper. 

the fix here uses these answers 
- https://github.com/facebook/react-native/issues/31179#issuecomment-829536845 (part 3)
- https://stackoverflow.com/a/67314652/1194644

### CODE REVIEW

**Comment by geastwood** [comment]
Thanks for the PR.
There is currently a PR on upgrading RN to 0.64, would this PR still relevant after the upgrade?

**Comment by geastwood** [comment]
I think it would be fine with 0.64, let's merge this.

**Review by geastwood — COMMENTED** [review]
LGTM

**Comment by ahoseinian** [comment]
@geastwood  nice, btw I created the develop branch here so maybe we can reserve the master to be merged when we want a new version of the app. sounds good?

**Comment by geastwood** [comment]
Sounds good.

**Pull request closed without merging**
